### ISSUE TITLE
Use of `std::shared_ptr`

### ISSUE THREAD

**Issue by Mubramaj** [Konijnendijk/C-MCTS#12]
First of all thank you for  sharing your implementation of MCTS in c++.
This is not an issue but more a question:

Why did you use `std::shared_ptr` for the Node parent and children ?  Also on the MCTS root node ? Why not just `uniq_ptr`

**Comment by Konijnendijk** [comment]
Hey @Mubramaj, thanks for your question and apologies for the delayed response. 

It's been a while since I touched this code. However, I believe I reconstructed my original reasoning. 

In `MCTS::calculateAction`, `MCTS::search` and `MCTS::select`, the code creates a copy of the `Node` pointers. At the same time, inside the tree the nodes also point to one another. 

A maybe even more compelling reason is that the tree data structure links both ways. If we have a simple tree A -> B -> C, then both A and C refer to B (either in `children`, or as `parent`). 

I hope this clarifies things. And (as C++ isn't really my specialty), would you have any recommendations to improve the code regarding this point, or anywhere else?
